WIP: rebuilding testing env

diff --git a/scripts/three-chainz b/scripts/three-chainz
--- a/scripts/three-chainz
+++ b/scripts/three-chainz
@@ -1,10 +1,7 @@
 #!/bin/bash
-# two-chainz creates two gaiad chains and configures the relayer to 
 
 SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-GAIA_DATA="$(pwd)/data"
-RELAYER_DIR="$(dirname $SCRIPTDIR)"
-RELAYER_CONF="$HOME/.relayer"
+CONFIG_DATA="$(pwd)/data"
 
 # Ensure gaiad is installed
 if ! [ -x "$(which gaiad)" ]; then
@@ -12,9 +9,18 @@ if ! [ -x "$(which gaiad)" ]; then
   exit 1
 fi
 
+# Ensure sommelier is installed
+if ! [ -x "$(which sommelier)" ]; then
+  echo "Error: sommelier is not installed. Try running 'make build-somm'" >&2
+  exit 1
+fi
+
 # Display software version for testers
 echo "GAIA VERSION INFO:"
 gaiad version --long
+
+echo "SOMMELIER VERSION INFO:"
+sommelier version --long
 
 # Ensure jq is installed
 if [[ ! -x "$(which jq)" ]]; then
@@ -24,8 +30,8 @@ if [[ ! -x "$(which jq)" ]]; then
 fi
 
 # Ensure user understands what will be deleted
-if [[ -d $GAIA_DATA ]] && [[ ! "$1" == "skip" ]]; then
-  read -p "$(basename $0) will delete \$(pwd)/data and \$HOME/.relayer folders. Do you wish to continue? (y/n): " -n 1 -r
+if [[ -d $CONFIG_DATA ]] && [[ ! "$1" == "skip" ]]; then
+  read -p "$(basename $0) will delete \$(pwd)/data folders. Do you wish to continue? (y/n): " -n 1 -r
   echo
   if [[ ! $REPLY =~ ^[Yy]$ ]]; then
       exit 1
@@ -33,49 +39,30 @@ if [[ -d $GAIA_DATA ]] && [[ ! "$1" == "skip" ]]; then
 fi
 
 # Delete data from old runs
-rm -rf $GAIA_DATA &> /dev/null
-rm -rf $RELAYER_CONF &> /dev/null
+rm -rf $CONFIG_DATA &> /dev/null
 
 # Stop existing gaiad processes
 killall gaiad &> /dev/null
-killall akash &> /dev/null
+killall sommelier &> /dev/null
 
-set -e
+# set -e
 
 chainid0=ibc-0
 chainid1=ibc-1
 chainid2=ibc-2
 
-echo "Generating gaia configurations..."
-mkdir -p $GAIA_DATA && cd $GAIA_DATA && cd ../
-./scripts/one-chain gaiad $chainid0 ./data 26657 26656 6060 9090
-./scripts/one-chain gaiad $chainid1 ./data 26557 26556 6061 9091
-./scripts/one-chain gaiad $chainid2 ./data 25557 25556 6062 9092
+# Spin up the 3 chain instances
+echo "Generating chain configurations..."
+mkdir -p $CONFIG_DATA && cd $CONFIG_DATA && cd ../
+./scripts/one-chain sommelier     $chainid0 ./data 26657 26656 6060 9090 1122
+./scripts/one-chain gaiad         $chainid1 ./data 26557 26556 6061 9900 1212
+./scripts/one-chain sommelier     $chainid2 ./data 25557 25556 6062 9990 2211
 
-[ -f $GAIA_DATA/$chainid0.log ] && echo "$chainid0 initialized. Watch file $GAIA_DATA/$chainid0.log to see its execution."
-[ -f $GAIA_DATA/$chainid1.log ] && echo "$chainid1 initialized. Watch file $GAIA_DATA/$chainid1.log to see its execution."
-[ -f $GAIA_DATA/$chainid2.log ] && echo "$chainid2 initialized. Watch file $GAIA_DATA/$chainid2.log to see its execution."
+[ -f $CONFIG_DATA/$chainid0.log ] && echo "$chainid0 initialized. Watch file $CONFIG_DATA/$chainid0.log to see its execution."
+[ -f $CONFIG_DATA/$chainid1.log ] && echo "$chainid1 initialized. Watch file $CONFIG_DATA/$chainid1.log to see its execution."
+[ -f $CONFIG_DATA/$chainid2.log ] && echo "$chainid2 initialized. Watch file $CONFIG_DATA/$chainid2.log to see its execution."
 
-cd $RELAYER_DIR
-
-echo "Building Relayer..."
-make install
-
-echo "Generating rly configurations..."
-rly config init
-rly config add-chains configs/three/chains
-
-SEED0=$(jq -r '.mnemonic' $GAIA_DATA/ibc-0/key_seed.json)
-SEED1=$(jq -r '.mnemonic' $GAIA_DATA/ibc-1/key_seed.json)
-SEED2=$(jq -r '.mnemonic' $GAIA_DATA/ibc-2/key_seed.json)
-echo "Key $(rly keys restore ibc-0 testkey "$SEED0") imported from ibc-0 to relayer..."
-echo "Key $(rly keys restore ibc-1 testkey "$SEED1") imported from ibc-1 to relayer..."
-echo "Key $(rly keys restore ibc-2 testkey "$SEED2") imported from ibc-2 to relayer..."
-
-rly config add-paths configs/three/paths
-
-echo "Creating light clients..."
-sleep 3
-rly light init ibc-0 -f
-rly light init ibc-1 -f
-rly light init ibc-2 -f
+# Spin up the 2 relayer instances
+./scripts/two-relayers
+# [ -f $CONFIG_DATA/$rlyid0.log ] && echo "$rlyid0 initialized. Watch file $CONFIG_DATA/$rlyid0.log to see its execution."
+# [ -f $CONFIG_DATA/$rlyid1.log ] && echo "$rlyid1 initialized. Watch file $CONFIG_DATA/$rlyid1.log to see its execution."
